//
//  Image.swift
//  domains-manager-ios
//
//  Created by Oleg Kuplin on 22.08.2023.
//

import SwiftUI

extension Image {
    
    static let cancelIcon = Image(uiImage: .cancelIcon)
    static let searchIcon = Image(uiImage: .searchIcon)
    static let messageCircleIcon24 = Image(uiImage: .messageCircleIcon24)
    static let messageCircleFilledIcon = Image("messageCircleFilledIcon")

    static let twitterIcon24 = Image(uiImage: .twitterIcon24)
    static let arrowTopRight = Image(uiImage: .arrowTopRight)
    static let plusIconNav = Image(uiImage: .plusIconNav)
    static let reputationIcon20 = Image(uiImage: .reputationIcon20)
    static let domainSharePlaceholder = Image(uiImage: .domainSharePlaceholder)
    static let grimaseIcon = Image(uiImage: .grimaseIcon)
    static let cellChevron = Image(uiImage: .cellChevron)
    static let chevronDown = Image(uiImage: .chevronDown)
    static let chevronUp = Image(uiImage: .chevronUp)
    static let checkCircle = Image(uiImage: .checkCircle)
    static let udCartLogoRaster = Image(uiImage: .udCartLogoRaster)
    static let crossWhite = Image(uiImage: .crossWhite)
    static let chevronRight = Image(uiImage: .chevronRight)
    static let check = Image(uiImage: .check)
    static let sparkleIcon = Image(uiImage: .sparkleIcon)
    static let statsIcon = Image(uiImage: .statsIcon)
    static let vaultIcon = Image(uiImage: .vaultIcon)
    static let tagsCashIcon = Image(uiImage: .tagsCashIcon)
    static let usaFlagIcon = Image(uiImage: .usaFlagIcon)
    static let appleIcon = Image(uiImage: .appleIcon)
    static let tagIcon = Image(uiImage: .tagIcon)
    static let udWalletListIcon = Image(uiImage: .udWalletListIcon)
    static let systemGlobe = Image(uiImage: .systemGlobe)
    static let infoIcon = Image(uiImage: .infoIcon)
    static let refreshIcon = Image(uiImage: .refreshIcon)
    static let magicWandIcon = Image(uiImage: .magicWandIcon)
    static let warningIcon = Image(uiImage: .warningIcon)
    static let tapSingleIcon = Image(uiImage: .tapSingleIcon)
    static let layoutGridEmptyIcon = Image(uiImage: .layoutGridEmptyIcon)
    static let squareBehindSquareIcon = Image(uiImage: .squareBehindSquareIcon)
    static let dotsIcon = Image(uiImage: .dotsIcon)
    static let personIcon = Image(uiImage: .personIcon)
    static let arrowBottom = Image(uiImage: .arrowBottom)
    static let filterIcon = Image(uiImage: .filterIcon).renderingMode(.template)
    static let settingsIcon = Image("settingsIcon")
    static let qrBarCodeIcon = Image("qrBarCodeIcon")
    static let homeLineIcon = Image("homeLineIcon")
    static let homeLineFilledIcon = Image("homeLineFilledIcon")
    static let chevronGrabberVertical = Image("chevronGrabberVertical")
    static let notesIcon = Image("notesIcon")
    static let vaultSafeIcon = Image("vaultSafeIcon")
    static let walletExternalIcon = Image("walletExternalIcon")
    static let checkCircleEmpty = Image("checkCircleEmpty")
    static let crownIcon = Image("crownIcon")
    static let threeLayersStack = Image("threeLayersStack")
    static let squareInfo = Image("squareInfo")
    static let chainLinkIcon = Image("chainLinkIcon")
    static let timeIcon = Image("timeIcon24")
    static let globeIcon = Image("globeIcon")
    static let logOutIcon = Image("logOutIcon24")
    static let wallet3Icon = Image("wallet3Icon")
    static let copyToClipboardIcon = Image("copyIcon")
    static let creditCard2Icon = Image("creditCard2Icon")
    static let shareFlatIcon = Image("shareFlatIcon")
    static let shareIcon = Image("shareIcon")
    static let web3ProfileIllustration = Image("web3ProfileIllustration")
    static let subdomainGridBackground = Image("subdomainGridBackground")
    static let udLogoBlue = Image("udLogoBlue")
    static let arrowUp24 = Image("arrowUp24")
    static let plusIcon18 = Image("plusIcon18")
    static let trashIcon = Image("trashIcon16")
    static let framesIcon = Image("framesIcon")
    static let helpIcon = Image("helpIcon24")
    static let docsIcon = Image("docsIcon24")
    static let dotsCircleIcon = Image("dotsCircleIcon")
    static let walletIcon = Image("walletIcon")
    static let createMessagingProfileIllustration = Image("createMessagingProfileIllustration")
    static let bellIcon = Image("bellIcon")
    static let settingsIconLock = Image("settingsIconLock")
    static let settingsIconTestnet = Image("settingsIconTestnet")
    static let settingsIconLearn = Image("settingsIconLearn")
    static let settingsIconTwitter = Image("settingsIconTwitter")
    static let settingsIconFeedback = Image("settingsIconFeedback")
    static let settingsIconLegal = Image("settingsIconLegal")
    static let gasFeeIcon = Image("gasFeeIcon")
    static let chatRequestsIcon = Image("chatRequestsIcon")
    static let alertOctagon24 = Image("alertOctagon24")
    static let newMessageIcon = Image("newMessageIcon")
    static let exploreIcon = Image("exploreIcon")
    static let exploreFilledIcon = Image("exploreFilledIcon")
    static let globeBold = Image("globeBold")
    static let searchClearIcon = Image("searchClearIcon")
    static let globeRotated = Image("globeRotated")
    static let verticalLines = Image("verticalLines")
    static let arrowDown = Image("arrowDown")
    static let paperPlaneTopRight = Image("paperPlaneTopRight")
    static let paperPlaneTopRightSend = Image("paperPlaneTopRightSend")
    static let arrowsTopBottom = Image("arrowsTopBottom")
    static let confirmSendTokenGrid = Image("confirmSendTokenGrid")
    static let chevronDoubleDown = Image("chevronDoubleDown")
    static let bolt = Image("bolt")
    static let boltSlash = Image("boltSlash")
    static let udLogoBlueSquare = Image("udLogoBlueSquare")
    static let clock = Image("clock")
    static let clockFilled = Image("clockFilled")
    static let brushSparkle = Image("brushSparkle")
    static let alertCircle = Image("alertCircle")
    static let mpcWalletGrid = Image("mpcWalletGrid")
    static let mpcWalletGridAccent = Image("mpcWalletGridAccent")
    static let addWalletIcon = Image("addWalletIcon")
    static let plusCircle = Image("plusCircle")
    static let settingsIconStar = Image("settingsIconStar")
    static let shieldKeyhole = Image("shieldKeyhole")
    static let cloudIcon = Image("cloudIcon")
    static let externalWalletIndicator = Image("externalWalletIndicator")
    static let mailIcon24 = Image("mailIcon24")
    static let peopleCircleIcon = Image("peopleCircleIcon")
    static let purchaseMPCIcon = Image("purchaseMPCIcon")
    static let mpcWalletRecoveryIllustration = Image("mpcWalletRecoveryIllustration")
    static let gas = Image("gas")
    
    static let cryptoFaceIcon = Image("cryptoFaceIcon")
    static let cryptoPOAPIcon = Image("cryptoPOAPIcon")
    static let cryptoTransactionIcon = Image("cryptoTransactionIcon")
    static let lensIcon = Image("lensIcon")
    static let farcasterIcon = Image("farcasterIcon")
    static let walletAddressesIcon = Image("walletAddressesIcon")
    static let layoutGridTwo = Image("layoutGridTwo")
    static let twoCoinsIcon = Image("twoCoinsIcon")
    static let filter = Image("filter")
    
    static let systemDocOnDoc = Image(systemName: "doc.on.doc")
    static let systemAppBadgeCheckmark = Image(systemName: "app.badge.checkmark")
    
    static let switcherIcon = Image("switcherIcon")
    static let balanceIcon = Image("balanceIcon")
    static let collectiblesIcon = Image("collectiblesIcon")
    static let messagesIcon = Image("messagesIcon")

}
